units = [
    "Arambai",
    "Arbalester",
    "Archer",
    "Armored Elephant",
    "Ballista Elephant",
    "Battering Ram",
    "Battle Elephant",
    "Berserk",
    "Blackwood Archer",
    "Bolas Rider",
    "Bombard Cannon",
    "Boyar",
    "Camel Archer",
    "Camel Rider",
    "Camel Scout",
    "Capped Ram",
    "Cataphract",
    "Cavalier",
    "Cavalry Archer",
    "Centurion",
    "Chakram Thrower",
    "Champi Runner",
    "Champi Scout",
    "Champi Warrior",
    "Champion",
    "Chu Ko Nu",
    "Composite Bowman",
    "Condottiero",
    "Conquistador",
    "Coustillier",
    "Crossbowman",
    "Eagle Scout",
    "Eagle Warrior",
    "Elephant Archer",
    "Elite Battle Elephant",
    "Elite Champi Warrior",
    "Elite Eagle Warrior",
    "Elite Elephant Archer",
    "Elite Fire Lancer",
    "Elite Skirmisher",
    "Elite Steppe Lancer",
    "Fire Archer",
    "Fire Lancer",
    "Flemish Militia",
    "Gbeto",
    "Genitour",
    "Genoese Crossbowman",
    "Ghulam",
    "Grenadier",
    "Guecha Warrior",
    "Halberdier",
    "Hand Cannoneer",
    "Hearth Troop",
    "Heavy Camel Rider",
    "Heavy Cavalry Archer",
    "Heavy Hei Guang Cavalry",
    "Heavy Mounted Crossbowman",
    "Heavy Scorpion",
    "Hei Guang Cavalry",
    "Houfnice",
    "Huskarl",
    "Hussar",
    "Hussite Wagon",
    "Ibirapema Warrior",
    "Imperial Camel Rider",
    "Imperial Skirmisher",
    "Iron Pagoda",
    "Janissary",
    "Jarl",
    "Jian Swordsman",
    "Jomsviking",
    "Kamayuk",
    "Karambit Warrior",
    "Keshik",
    "Kipchak",
    "Knight",
    "Kona",
    "Konnik",
    "Legionary",
    "Leitis",
    "Light Cavalry",
    "Long Swordsman",
    "Longbowman",
    "Magyar Huszar",
    "Mameluke",
    "Man-at-Arms",
    "Mangonel",
    "Mangudai",
    "Militia",
    "Missionary",
    "Monaspa",
    "Monk",
    "Mounted Crossbowman",
    "Mounted Trebuchet",
    "Obuch",
    "Onager",
    "Organ Gun",
    "Paladin",
    "Pikeman",
    "Plumed Archer",
    "Ratha",
    "Rattan Archer",
    "Samurai",
    "Savar",
    "Scorpion",
    "Scout Cavalry",
    "Serjeant",
    "Shotel Warrior",
    "Shrivamsha Rider",
    "Siege Elephant",
    "Siege Onager",
    "Siege Ram",
    "Siege Tower",
    "Skirmisher",
    "Slinger",
    "Spearman",
    "Steppe Lancer",
    "Temple Guard",
    "Teutonic Knight",
    "Throwing Axeman",
    "Tiger Cavalry",
    "Traction Trebuchet",
    "Trade Cart",
    "Trebuchet",
    "Turtle Ship",
    "Two-Handed Swordsman",
    "Varangian Guard",
    "Villager",
    "War Elephant",
    "War Wagon",
    "Warrior Priest",
    "White Feather Guard",
    "Winged Hussar",
    "Woad Raider",
    "Xianbei Raider",
    "Xolotl Warrior",
    # "Galley",
    # "War Galley",
    # "Galleon",
    # "Fire Galley",
    # "Fire Ship",
    # "Fast Fire Ship",
    # "Hulk",
    # "War Hulk",
    # "Carrack",
]


elite = [
    "Arambai",
    "Ballista Elephant",
    "Blackwood Archer",
    "Berserk",
    "Bolas Rider",
    "Boyar",
    "Camel Archer",
    "Caravel",
    "Cataphract",
    "Centurion",
    "Chakram Thrower",
    "Chu Ko Nu",
    "Composite Bowman",
    "Conquistador",
    "Coustillier",
    "Dismounted Konnik",
    "Fire Archer",
    "Flemish Militia",
    "Gbeto",
    "Genitour",
    "Genoese Crossbowman",
    "Ghulam",
    "Guecha Warrior",
    "Hearth Troop",
    "Huskarl",
    "Hussite Wagon",
    "Ibirapema Warrior",
    "Iron Pagoda",
    "Janissary",
    "Jarl",
    "Jian Swordsman",
    "Jomsviking",
    "Kamayuk",
    "Karambit Warrior",
    "Keshik",
    "Kipchak",
    "Kona",
    "Konnik",
    "Leitis",
    "Longbowman",
    "Magyar Huszar",
    "Mameluke",
    "Mangudai",
    "Monaspa",
    "Obuch",
    "Organ Gun",
    "Plumed Archer",
    "Ratha",
    "Rattan Archer",
    "Samurai",
    "Serjeant",
    "Shotel Warrior",
    "Shrivamsha Rider",
    "Temple Guard",
    "Teutonic Knight",
    "Throwing Axeman",
    "Tiger Cavalry",
    "Turtle Ship",
    "Urumi Swordsman",
    "War Elephant",
    "War Wagon",
    "White Feather Guard",
    "Woad Raider",
    "Xianbei Raider",
    # "Xolotl Warrior",
]
